api/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('students/', views.studentApiView),
    path('posts/', views.postApiView)
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('students/', views.student_view, name='students'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('assignments/', views.postView, name='assignment')
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

# WEB APP PATHS
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('api/v1/', include('api.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

api/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    regNo  = models.CharField(unique=True, max_length=10)
    name   = models.CharField(max_length=30)
    feeBal = models.IntegerField(default=0)

    def __str__(self):
        return self.name

 

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=200)
    publish_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from home.models import Student
from posts.models import Post
from django.http import JsonResponse
from .serializers import StudentSerializer, PostSerializer
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

# Create your views here.
@api_view(['GET', 'POST'])
def studentApiView(request):
    if request.method == "GET":
        # Display all students in the database
        students = Student.objects.all()
        serializer = StudentSerializer(students, many=True) #students can be multiple hence many=True
        return Response(serializer.data, status=status.HTTP_200_OK)
    elif request.method == "POST":
        serializer = StudentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def postApiView(request):
    if request.method == 'GET':
        posts      = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    elif request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

home/views.py
from django.shortcuts import render, redirect
from .models import Student
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.conf import settings

# Create your views here.

def index_view(request):
    return render(request, 'home/index.html')

# Custom decorator
def staff_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            returnUrl = request.get_full_path()
            loginUrl = reverse('users:login')
            return redirect(f"{loginUrl}?{REDIRECT_FIELD_NAME}={returnUrl}")
        elif not user.is_staff:
            return HttpResponse('Not authorized', status=401)
        return view_func(request, *args, **kwargs)
    return _wrapped_view

@staff_required
def student_view(request):
    students = Student.objects.all()
    return render(request, 'home/students.html', {'students': students})

posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.
def postView(request):
    posts = Post.objects.all()
    return render(request, 'posts/assignment.html', {'posts': posts})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.utils.http import url_has_allowed_host_and_scheme ## prevents open redirects
from django.conf import settings

# Create your views here.
def register_view(request):
    if request.user.is_authenticated:
        return redirect('home:index')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
        return redirect('home:index')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})



def login_view(request):
    next_url = request.GET.get('next') or request.POST.get('next')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if next_url and url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}):
	            return redirect(next_url)
            return redirect('home:index')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form, 'next': next_url})



def logout_view(request):
    logout(request)
    return redirect('users:login')

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}
<!-- Hero Section -->
<section class="bg-light text-dark text-center py-5">
    <div class="container-fluid">
        <h1 class="display-4 fw-bold text-primary">Welcome To MHS</h1>
        <p class="lead">Center for Excellence in Learning and Innovation</p>
    </div>
</section>

<!-- About Section -->
<section class="py-5">
    <div class="container-fluid px-4">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h2 class="text-secondary">Who We Are</h2>
                <p class="mt-3" id="about">
                    MHS is a leading institution dedicated to nurturing bright minds with integrity and
                    purpose. We offer top-tier academic programs and co-curricular activities that prepare our
                    students for the global stage.
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

home/templates/home/students.html
{% extends 'base.html' %}
{% block content %}
 {% for student in students %}
 <div class="row">
  <div class="col-md-4">
  <div class="card mt-5 mb-2 ml-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ student.name }}</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Fee Balance</h6>
      <p class="card-text">{{ student.feeBal }}</p>
    </div>
  </div>
  </div>
</div>
  {% empty %}
  <p class="text-center">No Students available</p>
  {% endfor %}
{% endblock %}

posts/templates/posts/assignment.html
{% extends 'base.html' %}
{% block content %}
    <div class="container m-5">
    <div class="rows">
        {% for post in posts %}
        <div class="col-4 m-3">
            <div class="card">
                <h3 class="card-title">{{ post.title }}</h3>
                <p class="card-text">{{ post.content }}</p>
            </div>
        </div>
        {% empty %}
        <p>No Assignment Available</p>
        {% endfor %}
    </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murunyu High School</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    
    <style>
        .navbar {
            background-color: #003f63; /* Match the blue color */
        }
        .navbar-brand img {
            height: 40px; /* Adjust the height of the logo as needed */
        }
        .nav-link {
            color: white !important;
        }
        .navbar-toggler-icon {
            background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
        }
        .slider-section .slide {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
            opacity: 0;
            transition: opacity 1s ease-in-out;
        }
        body, html {
            height: 100%;
        }
        body{
            display: flex;
            flex-direction: column;
            
        }
        main{
            flex: 1;
        }
        .info-section {
            background-color: #f8f9fa;
            padding: 40px 20px;
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-top: 2px solid #003f63;
        }
        .info-section .contact-info, .info-section .quick-links {
            color: #003f63;
        }
        .info-section .contact-info h5, .info-section .quick-links h5 {
            color: #003f63;
        }
        .info-section .social-icons a {
            margin-right: 10px;
            color: #003f63;
        }
        .info-section .social-icons a:hover {
            color: #ff9900;
        }
        
    </style>
</head>
<body>

        <nav class="navbar navbar-expand-lg w-100 mb-2">
            <a class="navbar-brand" href="#">
                <img rel="preload" src="https://raw.githubusercontent.com/tonythebughunter/MurunyuHigh/main/mhs%20logo.png" alt="Murunyu High School Logo">
            </a>
            <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}#about">  ABOUT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}#academics">  ACADEMICS</a>
                      
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:students' %}">  STUDENTS</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'posts:assignment' %}" class="nav-link"> ASSIGNMENT</a>
                        </li>
                        <li class="nav-item">
                            <form action="/users/logout/" method="post">
                                {% csrf_token %}
                                <button class="btn nav-link" type="submit">LOGOUT</button>
                            </form>
                        </li>
                    {% else %}                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}"> REGISTER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}"> LOGIN</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0 ms-3">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-facebook"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-twitter"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-instagram"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-youtube"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
        <main class="container">
            {% block content %}
            {% endblock %}
        </main>
        <div class="info-section d-flex justify-content-around align-items-start row mt-3">
            <div class="school-info text-center col">
                <img src="https://github.com/tonythebughunter/MurunyuHigh/raw/main/mhs%20logo.png" alt="Murunyu High School Logo" height="80">
                <div class="social-icons mt-2 col">
                    <a href="https://facebook.com"><i class="bi bi-facebook"></i></a>
                    <a href="https://twitter.com"><i class="bi bi-twitter"></i></a>
                    <a href="https://instagram.com"><i class="bi bi-instagram"></i></a>
                    <a href="https://youtube.com"><i class="bi bi-youtube"></i></a>
                </div>
            </div>
            <div class="contact-info col">
                <h5>Contact Us</h5>
                <p>P5W5+PCC, Nairobi</p>
                <p>Phone: 0797677193</p></br>
            </div>
            <div class="quick-links col m-2">
                <h5>Quick Links</h5>
                <ul class="list-unstyled">
                    <li><a href="https://medium.com">Blog</a></li>
                    <li><a href="#">Events</a></li>
                    <li><a href="#">Homework Help</a></li>
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                </ul>
            </div>
        </div>

    <footer class="bg-warning pt-4 pb-3">
        <p class="text-center">&copy; 2025 Anthony Mwangi</p>
    </footer>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <p>Already logged in, <a href="{% url 'home:index' %}">Go home</a></p>
    {% else %}
        <div class="container-fluid m-2">
            <div class="row">
                <div class="col-md-6 offset-sm-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h2 class="card-title text-center mb-4">Login Form</h2>
                            <form method="post" action="/users/login/">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="mb-3">
                                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                        {{ field }} <!--the form control ensures form is responsive to screen size changes-->
                                        {% if field.help_text %}
                                            <small class="form-text text-muted d-block">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                        {% if field.errors %}
                                            <div class="text-danger small">{{ field.errors|striptags }}</div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                                {% if next %}
                                <input type="hidden" name="next" value="{{ next }}">
                                {% endif %}
                                <button type="submit" class="btn btn-primary w-100">Login</button>
                                <p>Don't have an account? <a href="{% url 'users:register' %}">Create One</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid m-2">
    <div class="row">
        <div class="col-md-6 offset-sm-3">
            <div class="container-fluid">
            <div class="card shadow-sm pt-2">
                <div class="form-icon text-center h3 pt-3"><i class="bi bi-person-circle"></i></div>
                <h2 class="card-title text-center mb-4">Signup Form</h2>
                <div class="card-body">
                    <form method="post" action="/users/register/">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required aria-describedby="id_username_helptext" id="id_username">
                            
                                <small class="form-text text-muted d-block">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                            
                            
                        </div>
                    
                        <div class="mb-3">
                            <label for="id_password1" class="form-label">Password</label>
                            <input type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1">
                            
                                <small class="form-text text-muted d-block"><ul>
                                    <li>Your password can’t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li>
                                    <li>Your password can’t be entirely numeric.</li>
                                </ul>
                            </small>                                                       
                        </div>
                    
                        <div class="mb-3">
                            <label for="id_password2" class="form-label">Password</label>
                            <input type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2">
                            
                                <small class="form-text text-muted d-block">Enter the same password as before, for verification.</small>
                            
                            
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Submit</button>
                        <p>Have an account? <a href="{% url 'users:login' %}">Login</a></p>
                    </form>
                </div>
            </div>
        </div>       
        </div>
    </div>
</div>
{% endblock %}